port: 4000

theme: default

author: 

deploy:
 type: github
 repo: 
 branch: 
 message: Blogo deploy

social:
 twitter: 
 github: 
 weibo: 

comments: true
duoshuo_shortname: blogo

blogName: 

blogUrl: 

